using UnityEngine;
using UnityEngine.XR.Management;

// ASSIGNMENT 3 - PLUMBING. Not the point. You do not edit this file and you do not hand it in.
//
// In one line: when you press Play, try to start a VR headset. If there isn't one, switch on
// the keyboard-and-mouse simulator instead. Either way the scene runs.
//
// Why a script does this instead of a checkbox:
// Unity has a setting, "Initialize XR on Startup", that starts the headset for EVERY scene in
// the project. That would also start it for the knight-and-skeleton scenes, which are mouse
// games and look wrong inside a headset. So the setting is off, and the scenes that want VR
// ask for it themselves. This is the script that asks.
//
// Reading it is still worth two minutes, because it is the Lifecycle Lab again:
//   Awake      "I exist"        -> start the headset before anything else needs it
//   OnDestroy  "I'm going away" -> stop the headset when you press Stop

namespace Assignment3
{
    public class HeadsetOrSimulator : MonoBehaviour
    {
        // The XR Interaction Simulator object in the scene. It starts switched off.
        public GameObject simulator;

        // True only if THIS script started the headset. Then this script must also stop it.
        bool startedHeadset;

        void Awake()
        {
            // XRGeneralSettings holds what is ticked in Project Settings > XR Plug-in Management.
            // Its Manager is the thing that can start and stop a headset ("loader" is Unity's
            // word for the plug-in that talks to one kind of headset. Ours is OpenXR).
            XRManagerSettings xr = XRGeneralSettings.Instance != null ? XRGeneralSettings.Instance.Manager : null;

            // activeLoader == null means no headset is running yet. Try to start one.
            // If no headset is connected this fails, activeLoader stays null, and we carry on.
            if (xr != null && xr.activeLoader == null)
            {
                xr.InitializeLoaderSync();

                if (xr.activeLoader != null)
                {
                    xr.StartSubsystems();
                    startedHeadset = true;
                }
            }

            bool headsetRunning = xr != null && xr.activeLoader != null;

            // No headset? Switch the simulator on. Headset? Leave it off, or the keyboard and
            // the real controllers would fight over the same hands.
            if (simulator != null) simulator.SetActive(!headsetRunning);

            Debug.Log(headsetRunning
                ? "[Assignment 3] Headset found. Put it on."
                : "[Assignment 3] No headset found. Using the simulator: click the Game view, then see the README for the keys.");
        }

        void OnDestroy()
        {
            // We started it, so we stop it. Otherwise the headset stays on after you press Stop.
            if (!startedHeadset) return;

            XRManagerSettings xr = XRGeneralSettings.Instance.Manager;
            xr.StopSubsystems();
            xr.DeinitializeLoader();
        }
    }
}
